# directories for where files exist and where to ouput the files
# TODO make this work with relative path from CWD
DATA_DIR: "/Users/mani/Repos/CMSC630_Image_Analysis/datasets/Cancerous_cell_smears"
OUTPUT_DIR: "/Users/mani/Repos/CMSC630_Image_Analysis/datasets/output/"
WIN_DATA_DIR: "C:/Users/Owner/Desktop/CMSC630_Image_Analysis/datasets/Cancerous_cell_smears"
WIN_OUTPUT_DIR: "C:/Users/Owner/Desktop/CMSC630_Image_Analysis/datasets/output/"


# allows user to choose which channel to convert to greyscale from
# options: red, green, or blue
SELECTED_COLOR_CHANNEL: "red"

# value between 0-1
SNP_NOISE: 0.2
G_NOISE: 0.9

# python numeric data type as string, ie. double, int ...
QUANT_STRENGTH: "int"

# must be a 2D array of odd size equal to mask, 3x3=9, 5x5=25 ...
LINEAR_WEIGHT: [[1, 1, 1],
               [1, 1, 1],
               [1, 1 ,1]]

# must be a 2D array of odd size equal to mask, 3x3=9, 5x5=25 ...
MEDIAN_WEIGHT: [[1, 1, 1],
               [1, 1, 1],
               [1, 1 ,1]]