# directories for where files exist and where to ouput the files
# TODO make this work with relative path from CWD
DATA_DIR: "/Users/mani/Repos/CMSC630_Image_Analysis/datasets/Cancerous_cell_smears"
OUTPUT_DIR: "/Users/mani/Repos/CMSC630_Image_Analysis/datasets/output/"
WIN_DATA_DIR: "C:/Users/Owner/Desktop/CMSC630_Image_Analysis/datasets/Cancerous_cell_smears"
WIN_OUTPUT_DIR: "C:/Users/Owner/Desktop/CMSC630_Image_Analysis/datasets/output/"


# allows user to choose which channel to convert to greyscale from
# options: red, green, or blue
SELECTED_COLOR_CHANNEL: "red"

# value between 0-1
SNP_NOISE: 0.2
G_NOISE: 0.9

# must be a square, ie. 1,2,4,9,16...
LINEAR_MASK: 9